######################################################################
# Automatically generated by qmake (3.1) Sun Feb 1 23:13:57 2026
######################################################################

QT += widgets
SOURCES = lvl3proj2.cpp
TEMPLATE = app
TARGET = KIPFIN-LABWORK
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES += build/calculator_autogen/mocs_compilation.cpp \
           build/lvl1proj2_autogen/mocs_compilation.cpp \
           build/lvl1proj3_autogen/mocs_compilation.cpp \
           build/lvl1proj4_autogen/mocs_compilation.cpp \
           build/lvl1proj5_autogen/mocs_compilation.cpp \
           build/lvl2proj1_autogen/mocs_compilation.cpp \
           build/lvl2proj2_autogen/mocs_compilation.cpp \
           build/lvl2proj3_autogen/mocs_compilation.cpp \
           build/lvl2proj4_autogen/mocs_compilation.cpp \
           build/lvl3proj1_autogen/mocs_compilation.cpp \
           build/main_autogen/mocs_compilation.cpp \
           projects/cpp/src/calculator.cpp \
           projects/cpp/src/lvl1proj2.cpp \
           projects/cpp/src/lvl1proj3.cpp \
           projects/cpp/src/lvl1proj4.cpp \
           projects/cpp/src/lvl1proj5.cpp \
           projects/cpp/src/lvl2proj1.cpp \
           projects/cpp/src/lvl2proj2.cpp \
           projects/cpp/src/lvl2proj3.cpp \
           projects/cpp/src/lvl2proj4.cpp \
           projects/cpp/src/lvl3proj1.cpp \
           projects/cpp/src/lvl3proj2.cpp \
           projects/cpp/src/main.cpp \
           build/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.cpp
TRANSLATIONS += build/CMakeFiles/calculator.dir/compiler_depend.ts \
                build/CMakeFiles/calculator_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/calculator_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj2.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj2_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj2_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj3.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj3_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj3_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj4.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj4_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj4_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj5.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj5_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl1proj5_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj1.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj1_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj1_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj2.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj2_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj2_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj3.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj3_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj3_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj4.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj4_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl2proj4_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl3proj1.dir/compiler_depend.ts \
                build/CMakeFiles/lvl3proj1_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl3proj1_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/lvl3proj2.dir/compiler_depend.ts \
                build/CMakeFiles/lvl3proj2_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/lvl3proj2_autogen_timestamp_deps.dir/compiler_depend.ts \
                build/CMakeFiles/main.dir/compiler_depend.ts \
                build/CMakeFiles/main_autogen.dir/compiler_depend.ts \
                build/CMakeFiles/main_autogen_timestamp_deps.dir/compiler_depend.ts
